In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Convert excel to csv

In [3]:
excel_file_path = '../data/imdb_movies_2024.xlsx'

df = pd.read_excel(excel_file_path)

df.to_csv('../data/imdb_data.csv', index=False)

## Load data

In [4]:
movies_df = pd.read_csv('../data/imdb_data.csv')
movies_df.head()

,Movie_Title,Storyline
0,1. The Fall Guy,"A stuntman, fresh off an almost career-ending ..."
1,2. The Substance,A fading celebrity takes a black-market drug: ...
2,3. The Life of Chuck,"A life-affirming, genre-bending story about th..."
3,4. Abigail,After a group of criminals kidnap the ballerin...
4,5. The Ministry of Ungentlemanly Warfare,The British military recruits a small group of...

## Data Understanding

In [7]:
print("Dataset Shape")
print("="*30)
print("Total number of movies: ", movies_df.shape[0])
print("Total number of feature columns: ", movies_df.shape[1])
print("="*30)

print("Feature Datatypes")
print("="*30)
print(movies_df.dtypes)
print("="*30)

print("Missing values")
print("="*30)
print(movies_df.isnull().sum())
print("="*30)

print("Duplicate rows")
print("="*30)
print("Duplicate movies count: ", movies_df.duplicated().sum())
print("="*30)

print("Descriptive Statistics")
print("="*30)
movies_df['storyline_word_count'] = movies_df['Storyline'].apply(lambda x: len(str(x).split()))
print(movies_df['storyline_word_count'].describe())
print("="*30)

Dataset Shape
==============================
Total number of movies:  6021
Total number of feature columns:  3
==============================
Feature Datatypes
==============================
Movie_Title               str
Storyline                 str
storyline_word_count    int64
dtype: object
==============================
Missing values
==============================
Movie_Title             0
Storyline               0
storyline_word_count    0
dtype: int64
==============================
Duplicate rows
==============================
Duplicate movies count:  0
==============================
Descriptive Statistics
==============================
count    6021.000000
mean       32.730277
std        20.116917
min         4.000000
25%        24.000000
50%        30.000000
75%        37.000000
max       463.000000
Name: storyline_word_count, dtype: float64
==============================

In [6]:
print("Top 5 movies with the longest storylines")
print("="*30)
print(movies_df[['Movie_Title', 'storyline_word_count']].sort_values(by='storyline_word_count', ascending=False).head())
print("="*30)

print("Top 5 movies with the shortest storylines")
print("="*30)
print(movies_df[['Movie_Title', 'storyline_word_count']].sort_values(by='storyline_word_count', ascending=True).head())
print("="*30)

Top 5 movies with the longest storylines
==============================
                                            Movie_Title  storyline_word_count
4589  4590. Sureshinteyum Sumalathayudeyum Hridayaha...                   463
5969                                  5970. Troll Storm                   289
5316                                5317. Hotel Bitcoin                   277
4385                                    4386. Bloodline                   271
4570                               4571. What Ravens Do                   271
==============================
Top 5 movies with the shortest storylines
==============================
                Movie_Title  storyline_word_count
3247     3248. Stupid Games                     4
1019             1020. Saba                     6
5069          5070. Karaoké                     6
5176  5177. Astrid's Saints                     6
281              282. Waves                     6
==============================

## Data Cleaning

### Remove indexing in Movie_Title

In [ ]:
# remove numbering from the Movie_Title column
movies_df['Movie_Title'] = movies_df['Movie_Title'].str.replace(r'^\d+\.\s*', '', regex=True)
movies_df.head()

,Movie_Title,Storyline,storyline_word_count
0,The Fall Guy,"A stuntman, fresh off an almost career-ending ...",35
1,The Substance,A fading celebrity takes a black-market drug: ...,20
2,The Life of Chuck,"A life-affirming, genre-bending story about th...",17
3,Abigail,After a group of criminals kidnap the ballerin...,30
4,The Ministry of Ungentlemanly Warfare,The British military recruits a small group of...,23

### Clean Storyline column

In [9]:
import re

def clean_text(text):

    text = str(text)

    # Convert to lowercase
    text = text.lower()

    # Remove special characters
    text = re.sub(r"[^a-zA-Z\s]", " ", text)

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text


movies_df["clean_storyline"] = movies_df["Storyline"].apply(clean_text)
movies_df.tail()

,Movie_Title,Storyline,storyline_word_count,clean_storyline
6016,The Lamb,A gripping story about a man who was the terro...,28,a gripping story about a man who was the terro...
6017,Johatsu,A barber in a Roman neighborhood believes in o...,29,a barber in a roman neighborhood believes in o...
6018,Societat negra,"Follows David Edison, a cam-girl obsessed I.T....",27,follows david edison a cam girl obsessed i t g...
6019,El Ascenso,Simon Says is a thriller about a traumatized (...,30,simon says is a thriller about a traumatized p...
6020,Iron Fighter,Five high school students decide to do somethi...,26,five high school students decide to do somethi...

In [10]:
# save the cleaned dataframe to a new CSV file
movies_df.to_csv('../data/imdb_data_cleaned.csv', index=False)